### ISSUE TITLE
'Deepsid' does not name a type

### ISSUE THREAD

**Issue by LouDnl** [tobozo/ESP32-SIDView#1]
Hi, first, great project!

I'm trying to compile your project but am running into an issue.
The error I get is:
```c
SIDCacheManager.hpp:68:7: error: 'Deepsid' does not name a type; did you mean **'setsid'?**
```

At first I thought it was PlatformIO, but I get the same error in native Arduino IDE.

Any ideas?

**Comment by tobozo** [comment]
hi,

Deepsid support comes with [SID6581 library version 3.0.2](https://github.com/hpwit/SID6581/tree/3.0.2-beta)

**Comment by LouDnl** [comment]
Thanks, that fixed it! On to the next compile issue ;)

**Comment by tobozo** [comment]
yak shaving in progress 🤣
